beam: 300
clearml: false
datadir: /home/zhongwenkang/RawData_Processed/CoCoNut/bdj
modelpath: /home/zhongwenkang/Pretrained_Models/Processed_CoCoNut/CoCoNut_15_save/checkpoint_best.pt
nbest: 30
outputfile: /home/zhongwenkang/NPR4J_Pred/CoCoNut/CoCoNut_15_b300_bdj.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
