beam: 300
clearml: false
datadir: /home/zhongwenkang/RawData_Processed/CoCoNut/d4j
modelpath: /home/zhongwenkang/Pretrained_Models/Processed_CoCoNut/CoCoNut_context_tune_9_save/checkpoint_best.pt
nbest: 30
outputfile: /home/zhongwenkang/NPR4J_Pred/CoCoNut/CoCoNut_context_tune_9_b300_d4j.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
