model_path: /root/zwk/Recoder_models_ori/best_model.ckpt
ids_path: /root/zwk/BenchmarkData/bdj.ids.new
input_dir: /root/zwk/BenchmarkData
search_size: 400
classcontent_dir: /root/zwk/Recoder_Classcontent/Recoder
output_dir: /root/zwk/NPR4J_Pred/Recoder_ori_bdj
valdatapkl_f: /root/zwk/Recoder_models_ori/valdata.pkl
nl_voc_f: /root/zwk/Recoder_models_ori/nl_voc.pkl
rule_f: /root/zwk/Recoder_models_ori/rule.pkl
code_voc_path: /root/zwk/Recoder_models_ori/code_voc.pkl
char_voc_path: /root/zwk/Recoder_models_ori/char_voc.pkl
rulead_path: /root/zwk/Recoder_models_ori/rulead.pkl
NL_voc_size: 41696
code_voc_size: 41696
voc_size: 83
rule_num: 1265
cnum: 764