## Where the vocab(s) will be written
save_data: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w
# Prevent overwriting existing files in the folder
overwrite: True

# filter long examples
src_seq_length: 1010
tgt_seq_length: 1010
src_seq_length_trunc: 1010
tgt_seq_length_trunc: 1010

# common vocabulary for CoCoNut and target
share_vocab: True
dynamic_dict: True
# Corpus opts:
data:
    train:
        path_src: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/trn.buggy
        path_tgt: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/trn.fix
        transforms: []
        weight: 1
    valid:
        path_src: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/val.buggy
        path_tgt: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/val.fix
        transforms: []

src_vocab_size: 200000
tgt_vocab_size: 200000
src_vocab: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/idioms_10w.vocab
tgt_vocab: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/idioms_10w.vocab


decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

#add copy
copy_attn: true
copy_loss_by_seqlength: true
reuse_copy_attn: true

gpu_ranks: 0
global_attention: general
bridge: true

accum_count: 2
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 2048
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1
max_generator_batches: 2

warmup_steps: 6000
param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
train_steps: 500000
save_checkpoint_steps: 5000
valid_steps: 5000
valid_batch_size: 512
adagrad_accumulator_init: 0.1
early_stopping: 5
early_stopping_criteria: accuracy
seed: 912
world_size: 1

#model save and log
log_file: /root/zwk/DDPR_DATA/20878_CATufano_idiom10w_transformer+copy_wv512/20878_CATufano_idiom10w_transformer+copy_wv512.log
save_model: /root/zwk/DDPR_DATA/20878_CATufano_idiom10w_transformer+copy_wv512/20878_CATufano_idiom10w_transformer+copy_wv512
tensorboard: True
tensorboard_log_dir: /root/zwk/DDPR_DATA/20878_CATufano_idiom10w_transformer+copy_wv512/20878_CATufano_idiom10w_transformer+copy_wv512.tensorlog
